### ISSUE TITLE
Qiita・Xでの有効的な宣伝

### ISSUE THREAD

**Issue by kiyosan0517** [kiyosan0517/chari-log#128]
- QiitaとXでの宣伝を行なったものの、利用者を増やすことができないためどのような宣伝方法が適切かを相談したい

**Comment by Tsuchiya2** [comment]
こちら送信できてなかったようですみません🙇‍♂

---

自転車に関わるコミュニティに参加して、そのコミュニティ内での関係を構築してからサービスを紹介したりですかね。

あとはご自身でこのサービスを活用して投稿数を多くしていきながら、それをXに挙げたり、このサービスのニーズとマッチしそうなXのアカウントを洗い出して、関係構築を行い、適切なタイミングでこのサービスを試してもらうとかが取り組めることの1つかと考えました。
