### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [kiyosan0517/chari-log#95]
まずは、MVPのリリース、本当にお疲れ様でした。
アプリケーションが動作確認できました。LGTMです！

アプリケーションのさらなる改善に向けて、いくつかのポイントを挙げさせていただきます。これらは、ユーザー体験を高めるための提案ですので、スケジュールに合わせて順次検討いただければと思います。

```

■ユーザーページのエラー
https://charilog-ae3ab1d1c47c.herokuapp.com/users へのアクセス時にエラーが発生しているようです。原因の調査と修正をお願いします。

■検索条件のリセット機能
検索条件を簡単にリセットできるボタンの追加を検討してはいかがでしょうか？これによりユーザビリティが向上します。

■イイねボタンの明確化
現在、イイねボタンが一覧と詳細ページで2つ存在します。どちらを押せば良いか一目でわかるよう、デザインの調整をご検討ください。

■投稿編集のボタンテキスト
投稿を編集後の反映ボタンが「編集する」となっています。「更新する」のような文言の方が、動作をより明確に伝えられるかと思います。

■独自ドメインの対応
アプリケーションの信頼性を高めるため、独自ドメインへの対応を検討しましょう。

■検索のオートコンプリート機能
ユーザー体験向上のため、検索機能にオートコンプリートを導入することをお勧めします。

■Googleマップ
ログ投稿時に走行ルートをGoogleマップで表示できると、ユーザーにとって価値のある機能になる可能性があります。検討をお願いします。

■400, 500エラー系のページ用意
デフォルトのエラー画面ではなく、アプリケーションの世界観に沿ったエラーページを用意すると尚良いです。

```

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに修正完了までのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by kiyosan0517** [comment]
こちらこそ、迅速なご対応誠にありがとうございました。
挙げていただいたポイントに関して、以下のように対応を進めていきたいと思います。

### ■ユーザーページのエラー
こちらに関しては、まだ推測の域を出ませんが原因と思われるコードを発見したので早急に対応いたします。
Heroku logsで確認したところ、ActionView::Template::Error (ActiveStorage::FileNotFoundError)というエラーがありました。
アバター未登録のユーザーにアセットファイル内のsample.pngという画像データを紐づけるように対応しているのですが、その際に下記のようなコードで対応していたことが原因だと考えております。以下のような修正をする予定です。

```
# 現状のコード
app/models/user.rb
def default_image
  return if avatar.attached?

  sample_avatar = ActiveStorage::Blob.find_by(filename: 'sample.png')

  if sample_avatar
    avatar.attach(sample_avatar)
  else
    avatar.attach(io: File.open(Rails.root.join('app/assets/images/sample.png')),
                  filename: 'sample.png',
                  content_type: 'image/png')
  end
end

# 修正予定のコード
def default_image
  return if avatar.attached?

  if ActiveStorage::Blob.exists?(filename: 'sample.png')
    sample_avatar = ActiveStorage::Blob.find_by(filename: 'sample.png')
    avatar.attach(sample_avatar)
  else
    sample_avatar_path = asset_path('sample.png')
    avatar.attach(sample_avatar_path)
  end
end
```

### ■検索条件のリセット機能
こちらもissueを立てて早急に実装を進めます。

### ■イイねボタンの明確化
最近自分自身でもそのように感じていたので、こちらも早急に対応します。

### ■投稿編集のボタンテキスト
こちらもissueを立てて早急に実装を進めます。

### ■独自ドメインの対応
かしこまりました。ちなみに独自ドメインの取得に関しては、以前ググってみたところ様々な方法があったのですが、一般的に推奨される方法、おすすめの方法等はありますでしょうか？
もしあればご教授いただけると幸いです。よろしくお願いします。

### ■検索のオートコンプリート機能
こちらもissueを立てて早急に実装を進めます。

### ■Googleマップ
こちらは本リリースまでに対応する予定の機能だったので、エラー等の優先すべき対応が終わり次第着手したいと思います。

### ■400, 500エラー系のページ用意
自分自身でもあった方が薄々良いように感じていたので用意します。

issueを立て終えたらお話にもあった通り、こちらのissueはcloseさせていただきます。
ご対応ありがとうございました。

**Comment by Tsuchiya2** [comment]
@kiyosan0517 
> また書き出したissueをもとに修正完了までのスケジュールを教えていただけますでしょうか？

↑と本番リリースまでのスケジュールをMattermostのスレッドの方に返信いただけますか？
